version: '3.8'
name: container

services:	
    db:
      build: 
        context: .
        dockerfile: Database/Dockerfile
      restart: always
      container_name: dbPostgre
      environment:
        POSTGRES_DB: "questionnaire"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "f0e87ce7-b857-4bbc-907c-ff0ab90514ad"
      ports:
        - "65432:5432"
    web-api:
      build:
        context: .
        dockerfile: WebApplication1/Dockerfile
      container_name: App
      ports:
        - "64589:80"
      environment:
        - DOTNET_ENVIRONMENT=Development
        - ConnectionString= Server=host.docker.internal; Port=65432; Database=questionnaire; User Id=postgres; Password=f0e87ce7-b857-4bbc-907c-ff0ab90514ad;Include Error Detail=true;
   